name: CI

on:
  push:
    branches:
      - master
      - "feature/*"
      - "maint-**"
  pull_request:
    branches:
      - master
      - "maint-**"
      - "feature/**"
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 3 * * 6"
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason"
        required: false
        default: "Manual trigger"

jobs:
  Tests:
    uses: inveniosoftware/workflows/.github/workflows/tests-python.yml@master
    with:
      extras: "tests,admin,postgresql"
      search-service: '[""]'
